<a href="https://colab.research.google.com/github/estebanszd/Clase-Introducci-n-/blob/main/tarea_en_Clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
movies = pd.read_csv("https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/movies.csv")

ratings = pd.read_csv("https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/ratings.csv")

In [5]:
print(movies.shape)

print(ratings.shape)

(4803, 5)
(4803, 4)

In [16]:
print("Movies dataset")
print(movies.head())

print("Ratings dataset")
print(ratings.head())

Movies dataset
   Unnamed: 0     id                 title  popularity release_date
0           0    257          Oliver Twist   20.415572   2005-09-23
1           1  14290  Better Luck Tomorrow    3.877036   2002-01-12
2           2  38365             Grown Ups   38.864027   2010-06-24
3           3   9672              Infamous    3.680896   2006-11-16
4           4  12819       Alpha and Omega   12.300789   2010-09-17
Ratings dataset
   Unnamed: 0      id  vote_average  vote_count
0           0   19995           7.2     11800.0
1           1     285           6.9      4500.0
2           2  206647           6.3      4466.0
3           3   49026           7.6      9106.0
4           4   49529           6.1      2124.0

In [24]:
movie_ratings = movies.merge(ratings, on="id")

movie_ratings.head()

movie_ratings.drop(["Unnamed: 0_x", "Unnamed: 0_y"], axis = 1, inplace = True )

In [25]:

movie_ratings.head()

,id,title,popularity,release_date,vote_average,vote_count
0,257,Oliver Twist,20.415572,2005-09-23,6.7,274.0
1,14290,Better Luck Tomorrow,3.877036,2002-01-12,6.5,27.0
2,38365,Grown Ups,38.864027,2010-06-24,6.0,1705.0
3,9672,Infamous,3.680896,2006-11-16,6.4,60.0
4,12819,Alpha and Omega,12.300789,2010-09-17,5.3,124.0

In [26]:
movie_genres = pd.read_csv("https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/movie_to_genres.csv")

In [27]:
movie_genres.shape

(12160, 3)

In [28]:
movie_genres.head()

   Unnamed: 0  movie_id            genre
0           0         5            Crime
1           1         5           Comedy
2           2        11  Science Fiction
3           3        11           Action
4           4        11        Adventure

In [30]:
movie_genres.drop(["Unnamed: 0" ], axis = 1, inplace = True )

In [32]:
movies.drop(["Unnamed: 0" ], axis = 1, inplace = True )
print()

In [31]:
movie_genres.head()

   movie_id            genre
0         5            Crime
1         5           Comedy
2        11  Science Fiction
3        11           Action
4        11        Adventure

In [34]:
movie_generos = movies.merge(movie_genres, left_on="id", right_on="movie_id")

movie_generos.head()

      id                 title  popularity release_date  movie_id   genre
0    257          Oliver Twist   20.415572   2005-09-23       257   Crime
1    257          Oliver Twist   20.415572   2005-09-23       257   Drama
2    257          Oliver Twist   20.415572   2005-09-23       257  Family
3  14290  Better Luck Tomorrow    3.877036   2002-01-12     14290   Crime
4  14290  Better Luck Tomorrow    3.877036   2002-01-12     14290   Drama

In [43]:
movie_generos.sort_values(by='popularity', ascending=False).head()

           id         title  popularity release_date  movie_id      genre
11504  211672       Minions  875.581305   2015-06-17    211672  Animation
11503  211672       Minions  875.581305   2015-06-17    211672  Adventure
11502  211672       Minions  875.581305   2015-06-17    211672     Comedy
11505  211672       Minions  875.581305   2015-06-17    211672     Family
10954  157336  Interstellar  724.247784   2014-11-05    157336      Drama

In [52]:
movie_generos_action = movie_generos[movie_generos["genre"] == "Action"]

movie_generos_action

,id,title,popularity,release_date,movie_id,genre
11,49529,John Carter,43.926995,2012-03-07,49529,Action
20,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action
34,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action
71,19995,Avatar,150.437577,2009-12-10,19995,Action
79,27205,Inception,167.583710,2010-07-14,27205,Action
...,...,...,...,...,...,...
12099,34723,The Adventures of Huck Finn,2.163683,1993-04-02,34723,Action
12126,792,Platoon,49.802914,1986-12-18,792,Action
12140,116613,The Sweeney,6.938854,2012-09-11,116613,Action
12148,869,Planet of the Apes,51.188633,2001-07-25,869,Action
12156,13807,Exiled,8.486390,2006-09-06,13807,Action

In [53]:
movie_generos_action.shape

(1154, 6)

In [54]:
movie_generos_sci = movie_generos[movie_generos["genre"] == "Science Fiction"]

movie_generos_sci

,id,title,popularity,release_date,movie_id,genre
9,49529,John Carter,43.926995,2012-03-07,49529,Science Fiction
17,18841,The Lost Skeleton of Cadavra,1.680525,2001-09-12,18841,Science Fiction
21,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Science Fiction
46,26672,The Thief and the Cobbler,2.439184,1993-09-23,26672,Science Fiction
53,15301,Twilight Zone: The Movie,12.902975,1983-06-24,15301,Science Fiction
...,...,...,...,...,...,...
12032,5491,Battlefield Earth,7.891470,2000-05-10,5491,Science Fiction
12044,1576,Resident Evil,40.715623,2002-03-15,1576,Science Fiction
12052,13006,Split Second,4.857028,1992-05-01,13006,Science Fiction
12132,11058,Godsend,12.102350,2004-04-30,11058,Science Fiction
12146,869,Planet of the Apes,51.188633,2001-07-25,869,Science Fiction

In [55]:
movie_generos_sci.shape

(535, 6)

In [57]:
print(movie_generos_sci)

print(movie_generos_action)

          id                         title  popularity release_date  movie_id  \
9      49529                   John Carter   43.926995   2012-03-07     49529
17     18841  The Lost Skeleton of Cadavra    1.680525   2001-09-12     18841
21     76757             Jupiter Ascending   85.369080   2015-02-04     76757
46     26672     The Thief and the Cobbler    2.439184   1993-09-23     26672
53     15301      Twilight Zone: The Movie   12.902975   1983-06-24     15301
...      ...                           ...         ...          ...       ...
12032   5491             Battlefield Earth    7.891470   2000-05-10      5491
12044   1576                 Resident Evil   40.715623   2002-03-15      1576
12052  13006                  Split Second    4.857028   1992-05-01     13006
12132  11058                       Godsend   12.102350   2004-04-30     11058
12146    869            Planet of the Apes   51.188633   2001-07-25       869

                 genre
9      Science Fiction
17     Science Fiction
21     Science Fiction
46     Science Fiction
53     Science Fiction
...                ...
12032  Science Fiction
12044  Science Fiction
12052  Science Fiction
12132  Science Fiction
12146  Science Fiction

[535 rows x 6 columns]
           id                                             title  popularity  \
11      49529                                       John Carter   43.926995
20      76757                                 Jupiter Ascending   85.369080
34     308531  Teenage Mutant Ninja Turtles: Out of the Shadows   39.873791
71      19995                                            Avatar  150.437577
79      27205                                         Inception  167.583710
...       ...                                               ...         ...
12099   34723                       The Adventures of Huck Finn    2.163683
12126     792                                           Platoon   49.802914
12140  116613                                       The Sweeney    6.938854
12148     869                                Planet of the Apes   51.188633
12156   13807                                            Exiled    8.486390

      release_date  movie_id   genre
11      2012-03-07     49529  Action
20      2015-02-04     76757  Action
34      2016-06-01    308531  Action
71      2009-12-10     19995  Action
79      2010-07-14     27205  Action
...            ...       ...     ...
12099   1993-04-02     34723  Action
12126   1986-12-18       792  Action
12140   2012-09-11    116613  Action
12148   2001-07-25       869  Action
12156   2006-09-06     13807  Action

[1154 rows x 6 columns]

In [71]:
df_left = movie_generos_action.merge(movie_generos_sci, on="movie_id", how ="left", suffixes=("_action", "_sci"))

In [72]:
df_left.shape

(1154, 11)

In [73]:
df_left.head()

,id_sci,title_sci,popularity_sci,release_date_sci,movie_id,genre_sci,id_action,title_action,popularity_action,release_date_action,genre_action
0,49529,John Carter,43.926995,2012-03-07,49529,Action,49529.0,John Carter,43.926995,2012-03-07,Science Fiction
1,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action,76757.0,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
2,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action,NaN,NaN,NaN,NaN,NaN
3,19995,Avatar,150.437577,2009-12-10,19995,Action,19995.0,Avatar,150.437577,2009-12-10,Science Fiction
4,27205,Inception,167.583710,2010-07-14,27205,Action,27205.0,Inception,167.583710,2010-07-14,Science Fiction

In [76]:
df_right = movie_generos_action.merge(movie_generos_sci, on="movie_id", how ="right", suffixes=("_action", "_sci"))

In [77]:
df_right.head()

,id_action,title_action,popularity_action,release_date_action,movie_id,genre_action,id_sci,title_sci,popularity_sci,release_date_sci,genre_sci
0,49529.0,John Carter,43.926995,2012-03-07,49529,Action,49529,John Carter,43.926995,2012-03-07,Science Fiction
1,NaN,NaN,NaN,NaN,18841,NaN,18841,The Lost Skeleton of Cadavra,1.680525,2001-09-12,Science Fiction
2,76757.0,Jupiter Ascending,85.369080,2015-02-04,76757,Action,76757,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
3,NaN,NaN,NaN,NaN,26672,NaN,26672,The Thief and the Cobbler,2.439184,1993-09-23,Science Fiction
4,NaN,NaN,NaN,NaN,15301,NaN,15301,Twilight Zone: The Movie,12.902975,1983-06-24,Science Fiction

In [78]:
df_right.shape

(535, 11)